WifiDisplaySource: Remove kPlaybackSessionTimeoutUs static keyword
Summary:
Fixes the following:
frameworks/av/media/libstagefright/wifi-display/source/WifiDisplaySource.cpp:1036:
error: undefined reference to 'android::WifiDisplaySource::kPlaybackSessionTimeoutUs'

The reasoning:
Clang keeps the declaration of kPlaybackSessionTimeoutUs only visbile inside android::WifiDisplaySource
due to being of static const. However when operating on CHECK_OP, the declaration of
kPlaybackSessionTimeoutUs is no longer available to expand outside of android::WifiDisplaySource.

There are a few potential solutions to this issue as verified from build and testcase intermediates:
  - kPlaybackSessionTimeoutUs may be declared again prior to the first macro's use.
  - Both macros may be moved and defined prior to CHECK_GT's use in android::WifiDisplaySource.
  - Removal of the static keyword to change clang's behavior and allow kPlaybackSessionTimeoutUs
    to be expanded outside android::WifiDisplaySource.

The last option seemed to be the best solution for this issue.

Test Plan: verified

Reviewers: randall.rushing

Differential Revision: http://review.codefirex.com/D381